const SET_THEME = 'SET_THEME';
const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
const SET_USER = 'SET_USER';
const UNSET_USER = 'UNSET_USER'
const ADD_FAVOURITE = 'ADD_FAVOURITE'

export { SET_THEME, SET_SEARCH_QUERY, SET_USER, UNSET_USER, ADD_FAVOURITE };
